### ISSUE TITLE
Ability to disable/blacklist short link alias generators

### ISSUE THREAD

**Issue by d1snin** [linda-project/linda#14]
The app user should be able to disable some of the alias generators, for example:
```yaml
linda:
  alias-generators:
    disable: "custom,crc32" # comma separated list (for better env vars supprt)
```
